// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Week10Day1Demo_EfCore_DbFirst.Models
{
    public partial class Student
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public double? Percentage { get; set; }
    }
}